server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: OrderHub
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  flyway:
    enabled: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}

logging:
  structured:
    format:
      console: logstash

app:
  jwt:
    secret: ${JWT_SECRET}
    access-token-expiration: ${ACCESS_TOKEN_EXPIRATION}
    refresh-token-expiration: ${REFRESH_TOKEN_EXPIRATION}
    cookie-secure: ${JWT_COOKIE_SECURE:true}
