CREATE TABLE "users" (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(100)  NOT NULL,
    hash_password VARCHAR(255)  NOT NULL,
    full_name     VARCHAR(255),
    role          VARCHAR(50)   NOT NULL,
    created_at     TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ    NOT NULL DEFAULT now(),
    CONSTRAINT uq_users_username UNIQUE (username)
);

CREATE TABLE products (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku        VARCHAR(64)    NOT NULL,
    name       VARCHAR(255)   NOT NULL,
    category   VARCHAR(100),
    unit_price NUMERIC(19, 2) NOT NULL,
    currency   VARCHAR(3)     NOT NULL,
    stock      INTEGER        NOT NULL DEFAULT 0,
    is_active  BOOLEAN        NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ    NOT NULL DEFAULT now(),
    CONSTRAINT uq_products_sku UNIQUE (sku)
);

CREATE TABLE "orders" (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT         NOT NULL,
    code         VARCHAR(64)    NOT NULL,
    status       VARCHAR(50)    NOT NULL,
    total_amount NUMERIC(19, 2) NOT NULL,
    created_at    TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ    NOT NULL DEFAULT now(),
    CONSTRAINT uq_orders_code UNIQUE (code),
    CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES "users" (id)
);

CREATE TABLE order_items (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id   BIGINT         NOT NULL,
    product_id BIGINT         NOT NULL,
    quantity   INTEGER        NOT NULL,
    unit_price NUMERIC(19, 2) NOT NULL,
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES "orders" (id),
    CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES products (id)
);

CREATE TABLE payments (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id     BIGINT         NOT NULL,
    provider_ref VARCHAR(255),
    amount       NUMERIC(19, 2) NOT NULL,
    status       VARCHAR(50)    NOT NULL,
    paid_at      TIMESTAMPTZ,
    CONSTRAINT fk_payments_order FOREIGN KEY (order_id) REFERENCES "orders" (id)
);

CREATE TABLE invoices (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    BIGINT       NOT NULL,
    storage_key VARCHAR(512) NOT NULL,
    mime_type   VARCHAR(127),
    size_bytes  BIGINT,
    uploaded_at TIMESTAMPTZ,
    CONSTRAINT fk_invoices_order FOREIGN KEY (order_id) REFERENCES "orders" (id)
);

CREATE TABLE audit_logs (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id     BIGINT      NOT NULL,
    entity       VARCHAR(100) NOT NULL,
    entity_id    BIGINT       NOT NULL,
    action       VARCHAR(50)  NOT NULL,
    payload_json JSONB,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT fk_audit_logs_actor FOREIGN KEY (actor_id) REFERENCES "users" (id)
);

CREATE INDEX idx_order_user_id ON "orders" (user_id);
CREATE INDEX idx_order_items_order_id ON order_items (order_id);
CREATE INDEX idx_order_items_product_id ON order_items (product_id);
CREATE INDEX idx_payments_order_id ON payments (order_id);
CREATE INDEX idx_invoices_order_id ON invoices (order_id);
CREATE INDEX idx_audit_logs_actor_id ON audit_logs (actor_id);
CREATE INDEX idx_audit_logs_entity ON audit_logs (entity, entity_id);
