ALTER TABLE products
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

CREATE TABLE idempotency_keys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key VARCHAR(128) NOT NULL,
    user_id BIGINT NOT NULL,
    operation VARCHAR(100) NOT NULL,
    request_hash CHAR(64) NOT NULL,
    status VARCHAR(20) NOT NULL,
    response_status INT,
    response_body TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_idempotency_keys_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uq_idempotency_key
        UNIQUE (user_id, operation, key),
    CONSTRAINT chk_idempotency_status
        CHECK (status IN ('IN_PROGRESS', 'COMPLETED'))
);
